apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ubuntu
  name: ubuntu
spec:
  containers:
  - command:
    - sleep
    - "9999"
    image: ubuntu
    name: badboy
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
