kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    metadata:
      name: config
    apiServer:
      extraArgs:
        "encryption-provider-config": "/etc/kubernetes/pki/enc.yml"
nodes:
- role: control-plane
  extraMounts:
  - hostPath: ../enc
    containerPath: /etc/kubernetes/pki
- role: worker
- role: worker
- role: worker
