apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: nginx
    volumeMounts:
    - name: sekret
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: sekret
    secret:
      secretName: sekret
